// Builds src/generated/locales.js from messages/*.json, so adding a language is just adding a file.
// Runs automatically before dev, build and test (see package.json "pre*" scripts).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT = "ar";
const codes = fs
  .readdirSync(path.join(root, "messages"))
  .filter((f) => /^[a-z]{2}\.json$/.test(f))
  .map((f) => f.slice(0, 2))
  .sort((a, b) => (a === DEFAULT ? -1 : b === DEFAULT ? 1 : a.localeCompare(b)));

for (const code of codes) {
  const m = JSON.parse(fs.readFileSync(path.join(root, "messages", `${code}.json`), "utf8"));
  if (!m.meta || m.meta.code !== code || !["rtl", "ltr"].includes(m.meta.dir)) {
    throw new Error(`messages/${code}.json: meta.code must be "${code}" and meta.dir "rtl" or "ltr"`);
  }
}

const out = `// GENERATED by scripts/gen-locales.mjs from messages/*.json — do not edit.
${codes.map((c) => `import ${c} from "../../messages/${c}.json";`).join("\n")}

export const DEFAULT_LOCALE = "${DEFAULT}";
export const LOCALES = ${JSON.stringify(codes)};
export const MESSAGES = { ${codes.join(", ")} };
`;
fs.mkdirSync(path.join(root, "src", "generated"), { recursive: true });
fs.writeFileSync(path.join(root, "src", "generated", "locales.js"), out);
console.log(`locales: ${codes.join(", ")}`);
