-- Production schema for the book story-submission app.
-- Apply this in Supabase SQL editor or with the Supabase CLI.

create extension if not exists pgcrypto;

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  selected_language text not null,
  full_name text not null,
  phone_number text not null,
  email text not null,
  country text not null,
  country_code text not null default '',
  receipt_image jsonb not null,
  story_text text,
  story_images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists submissions_phone_number_key on public.submissions (phone_number);
create unique index if not exists submissions_email_key on public.submissions (lower(email));
create index if not exists submissions_selected_language_idx on public.submissions (selected_language);
create index if not exists submissions_country_idx on public.submissions (country);
create index if not exists submissions_country_code_idx on public.submissions (country_code);
create index if not exists submissions_created_at_idx on public.submissions (created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_submissions_updated_at on public.submissions;
create trigger set_submissions_updated_at
before update on public.submissions
for each row
execute function public.set_updated_at();

alter table public.submissions enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'receipts',
    'receipts',
    false,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif']
  ),
  (
    'story-pages',
    'story-pages',
    false,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/heic', 'image/heif']
  )
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
